/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { InsuranceRegistry__factory } from "./InsuranceRegistry__factory";
export { LoanContract__factory } from "./LoanContract__factory";
export { Marketplace__factory } from "./Marketplace__factory";
export { StablecoinMock__factory } from "./StablecoinMock__factory";
export { VehicleNFT__factory } from "./VehicleNFT__factory";
