/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InsuranceRegistry } from "./InsuranceRegistry";
export type { LoanContract } from "./LoanContract";
export type { Marketplace } from "./Marketplace";
export type { StablecoinMock } from "./StablecoinMock";
export type { VehicleNFT } from "./VehicleNFT";
